# Generated by Django 5.1.4 on 2024-12-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estacionamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('codigo_unico', models.CharField(editable=False, max_length=8, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='estacionamiento',
        ),
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='espacio',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='estacionamiento',
        ),
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='estacionamiento',
        ),
        migrations.RemoveField(
            model_name='registrovehiculo',
            name='tipo_vehiculo',
        ),
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.DeleteModel(
            name='Espacio',
        ),
        migrations.DeleteModel(
            name='Incidente',
        ),
        migrations.DeleteModel(
            name='Estacionamiento',
        ),
        migrations.DeleteModel(
            name='RegistroVehiculo',
        ),
        migrations.DeleteModel(
            name='TipoVehiculo',
        ),
    ]
