# Generated by Django 5.1.4 on 2024-12-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estacionamientos', '0002_usuario_remove_estacionamiento_administrador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=128)),
                ('codigo_unico', models.CharField(editable=False, max_length=8, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
