# Generated by Django 5.1.4 on 2024-12-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estacionamientos', '0006_registrovehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipovehiculo',
            old_name='tarifa',
            new_name='tarifa_por_hora',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='estacionamiento',
        ),
        migrations.RemoveField(
            model_name='espacio',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='estacionamiento',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='tipovehiculo',
            name='estacionamiento',
        ),
        migrations.AlterField(
            model_name='estacionamiento',
            name='espacios_totales',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_estacionamientos.espacio')),
            ],
        ),
    ]
