# Generated by Django 5.1.4 on 2024-12-18 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estacionamientos', '0007_rename_tarifa_tipovehiculo_tarifa_por_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovehiculo',
            name='hora_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
