# Generated by Django 5.1.4 on 2024-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_estacionamientos', '0008_alter_registrovehiculo_hora_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrovehiculo',
            name='hora_entrada',
            field=models.DateTimeField(),
        ),
    ]
